디자인 시스템 Button 구현
mash-up-kr/TwoToo_iOS pull request #14
Opened 2023-06-19 08:52 UTC by kimkyunghun3

## 개요
- 디자인 시스템 Button을 작업합니다.

## 변경사항
- 챌린지 추천 버튼 구현
- 챌린지 인증 버튼 구현

## 스크린샷
**챌린지  추천 버튼(선택된화면)**
<img src ="https://github.com/mash-up-kr/TwoToo_iOS/assets/52434820/195d00d7-e47c-407f-a88a-daf0d0ef4b86" height="700">

**챌린지 인증 버튼** 
| longCommit | mediumCommit | smallCommit |
|:---:|:---:|:---:|
|<img src ="https://github.com/mash-up-kr/TwoToo_iOS/assets/52434820/9b422030-6bf5-47d4-b34c-0993c50c21c2" width ="200">|<img src ="https://github.com/mash-up-kr/TwoToo_iOS/assets/52434820/ed31fafe-a1ca-42cd-8804-2019330c7864" width ="200">|<img src ="https://github.com/mash-up-kr/TwoToo_iOS/assets/52434820/d2ff3a94-9abf-4444-841d-942e1ff08db6" width ="200">|

2023-06-19 09:17 UTC, gunoooo requested changes
수고하셨습니다. 외부에서 사용할 때를 유의하여 몇개 커멘트 남겼습니다.

2023-06-19 09:17 UTC, gunoooo commented on Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTButton.swift
> +            isCommitEnabled(isCommitEnabled)
아직 헷갈릴수는 있겠지만 `self` 쓰는 컨벤션으로 하기로 했으니 전체적으로 한번 더 훑어 보셔야할거 같아요

2023-06-19 09:17 UTC, gunoooo commented on Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTChallengeButton.swift
> +public class TTChallengeButton: UIButton, UIComponentBased {
디자인 시스템에 도메인 용어가 들어가는건 구조상 좋지 않아보입니다.
Large, Small, Primary 등 조금 더 유연하게 사용 가능하도록 변경이 필요해보입니다.

2023-06-19 09:17 UTC, gunoooo commented on Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTButton.swift
> +    /*
스타일쉐어 컨벤션에 따라 /* */ 주석 말고 /// 주석을 사용해주세요

2023-06-19 09:17 UTC, gunoooo commented on Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTChallengeButton.swift
> +import SnapKit
이미 해당 모듈에 @_exported import 로 임포트되어있어 스냅킷 임포트는 불필요해보입니다.

2023-06-19 09:17 UTC, gunoooo commented on Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTCommitButton.swift
> +        var buttonWidth: CGFloat {
`width`, `height` 를 이렇게 고정하면 안될거 같습니다.

큰거는 
- 가로 : 화면 전체로 늘어진 길이
- 세로 : 패딩 18.5에 맞춰진 길이
중간은
- 가로 : 화면의 3/4
- 세로 : 패딩 18.5에 맞춰진 길이
작은거는
- 가로 : 패딩 11에 맞춰진 길이
- 세로 : 패딩 6에 맞춰진 길이

로 보입니다.

가로 세로를 이렇게 고정하면 텍스트와 프레임에 따라 보이는게 자연스럽지 못할겁니다. 
조금더 유연하게 만들어져야할거 같습니다.

2023-06-19 12:32 UTC, julia0926 commented
구웃~! 수고하셨습니다👏🏻👏🏻
버튼 파일들이 여러개 인 것 같은데 폴더로 묶어주면 더 좋을 것 같아요!

2023-06-19 13:10 UTC, kimkyunghun3 commented on Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTButton.swift
> +    /*
[b367964](https://github.com/mash-up-kr/TwoToo_iOS/pull/14/commits/b36796435ef2993d54c58316f9b8b9aa627bbf91)
수정했습니다!

2023-06-19 13:10 UTC, kimkyunghun3 commented on Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTChallengeButton.swift
> +import SnapKit
[b367964](https://github.com/mash-up-kr/TwoToo_iOS/pull/14/commits/b36796435ef2993d54c58316f9b8b9aa627bbf91)
아! 삭제했습니다!

2023-06-19 13:10 UTC, kimkyunghun3 commented on Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTButton.swift
> +            isCommitEnabled(isCommitEnabled)
전체적으로 수정해두었습니다!! 담부터 신경쓰겠습니다!

2023-06-19 13:37 UTC, kimkyunghun3 commented on Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTChallengeButton.swift
> +public class TTChallengeButton: UIButton, UIComponentBased {
https://github.com/mash-up-kr/TwoToo_iOS/pull/14/commits/75d0cceb6ef389fe237a87d03baecc95dc4180ae
요렇게 네이밍 및 주석도 유연하게 바꾸었는데 의도한게 맞을까요?

2023-06-21 02:05 UTC, kimkyunghun3 commented
디스코드로 리뷰가 이루어짐
**디자인 시스템에 대한 정의 확인**
특정되어 있지 않고 light, strong하게 설계되어야 한다.
'인증하기' 버튼이 아니라 동일 사이즈로 어떤 word의 버튼이 오더라도 수용할 수 있는 유연함이 있어야 한다.
인증하기기 버튼으로 특정지어 버리면, 찌르기 버튼 같은 곳에서는 사용하기 애매할 수 있음.
디자인 시스템에 하나의 기능이 담기지 않아야 하며 하나의 UI 성격으로 담겨져야 한다.

**유연한 레이아웃 설정**
일반적인 width, height, leading 등으로 하는 것이 아니라 UIScreen과 같이 스크린 사이즈를 기반으로 레이아웃을 형성해야한다.
그래야 다양한 프레임에 동적으로 보여줄 수 있다.

2023-06-22 01:29 UTC, closed without merging

2023-06-23 09:09 UTC, kimkyunghun3 commented on Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTCommitButton.swift
> +    var customButtonType: CustomButtonType = .longCommit
이거 교체했습니다!

2023-06-23 09:10 UTC, kimkyunghun3 commented on Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTCommitButton.swift
> +        var buttonWidth: CGFloat {
다음 PR에서 처리했습니다~