공통 컴포넌트 TagView 작업
mash-up-kr/TwoToo_iOS pull request #29
Opened 2023-07-05 00:35 UTC by julia0926

## 개요
공통으로 사용되는 태그뷰를 구현했습니다.
유연한 사용을 위해 내부 컨스트레인트만 잡았습니다. 
크기는 사용하는 쪽에서 정해야 합니다.

## 변경사항
- 작은 사이즈의 태그뷰
## 스크린샷
<img src="https://github.com/mash-up-kr/TwoToo_iOS/assets/37897873/bd54669f-e583-456b-a791-09fc4fae7ffc" width="300" height="650"/>

2023-07-05 01:50 UTC, gunoooo approved these changes
LGTM
확인했습니다~!

간단히 커멘트 남겼는데 확인부탁드릴게요

2023-07-05 01:50 UTC, gunoooo commented on Core/DesignSystem/Sources/DesignSystem/Sources/Component/TagView/TTTagView.swift
> +public final class TTTagView: UIView {
공통 뷰에는 `UIComponentBased`를 채택해야할거 같아요~

2023-07-05 01:50 UTC, gunoooo commented on Core/DesignSystem/Sources/DesignSystem/Sources/Component/TagView/TTTagView.swift
> +    lazy var titleLabel: UILabel = {
런타임중에 Tag 의 title 을 수정하고자 하는 니즈가 있을거 같아요
관련 프로퍼티를 만들거나 titleLabel 자체를 public 으로 하는 방법도 검토해보면 좋을거 같아요

2023-07-06 01:28 UTC, kimkyunghun3 requested changes
고생했습니다!!

2023-07-06 01:28 UTC, kimkyunghun3 commented on TwoToo/ViewController.swift
> +    lazy var tag2View: TTTagView = {
요거 네이밍이 바뀌면 좋을거같아요
디데이를 알려주는거라면 ddayTagView같은 느낌이면 좋을거같아요!

2023-07-06 01:28 UTC, kimkyunghun3 commented on TwoToo/ViewController.swift
> +    lazy var tagView: TTTagView = {
요것도 만약 tagView가 2가지면 각각 성격에 맞는 네이밍이면 좋을거같아요

2023-07-06 01:28 UTC, kimkyunghun3 commented on TwoToo/ViewController.swift
> +
불필요한 공백 지워도좋을거같아요!

2023-07-06 07:07 UTC, julia0926 commented on TwoToo/ViewController.swift
> +    lazy var tagView: TTTagView = {
요건 그냥 테스트용 뷰컨이라.. 무시하셔두 댑니다 ~! 위에 TagView만 봐주세용!

2023-07-06 07:07 UTC, julia0926 commented on TwoToo/ViewController.swift
> +    lazy var tag2View: TTTagView = {
위와 동일!

2023-07-06 07:07 UTC, julia0926 commented on TwoToo/ViewController.swift
> +
위와 동일!

2023-07-06 14:22 UTC, merged