Utils 관련 메서드 작업
mash-up-kr/TwoToo_iOS pull request #4
Opened 2023-06-09 14:46 UTC by kimkyunghun3

## 개요
Utils로 사용되는 메서드 작업합니다.

## 변경사항
각 메서드의 활용 용도에 대한 내용입니다.

- addAction, addTapAction : `action 추가`
- DateFormatter : `Date format 변환`
- Optional : `옵셔널 제거`
- UICollectionView : `header footer 재사용, cell 등록`
- UITableView : `header footer 재사용, cell 등록`
- UIStackView, UIView : `뷰 추가`

## 스크린샷
UI 관련 작업 없음

2023-06-13 05:00 UTC, julia0926 commented
공통으로 사용되는 utils가 많네요!! 
넘 수고하셨습니다 👍
위의 코멘트들 한번만 확인 부탁드려요~ 🙇🏻‍♀️

2023-06-13 08:45 UTC, kimkyunghun3 commented on Core/Util/Sources/Util/SceneUtils/UICollectionReusableView+.swift
> +    static var identifier: String {
header와 footer를 재사용하는 상황이 혹시? 있을 수 있어서 이곳에서 사용합니다! dequeueHeader, dequeueFooter에서 사용하고 있습니다

2023-06-13 08:49 UTC, kimkyunghun3 commented on Core/Util/Sources/Util/SceneUtils/DateFormatter.swift
> +    func format(_ type: FormatType) -> String {
이렇게 만든 이유는 서버에서 보통 시간 값을 json String으로 내려주기 때문에 String -> Date -> String 이렇게 해야 원하는 형식으로 변환할 수 있어서 그랬습니다!

2023-06-13 08:50 UTC, kimkyunghun3 commented on Core/Util/Sources/Util/SceneUtils/DateFormatter.swift
> + label.text = "2023:12:25".format(.yearMonthDay)
네네 예시에서 그렇고 디자인에서도 `2023/12/25` 처럼 /로 구분하는 변환이 있어서 일단 이걸 기본으로 만들어두었습니다!

2023-06-13 09:08 UTC, kimkyunghun3 commented on Core/Util/Sources/Util/SceneUtils/DateFormatter.swift
> +//  File.swift
https://github.com/mash-up-kr/TwoToo_iOS/pull/4/commits/a1fd6abd771c494982659eb8958a5cafb08cc05d
수정했습니다!

2023-06-13 09:08 UTC, kimkyunghun3 commented on Core/Util/Sources/Util/SceneUtils/UICollectionView.swift
> +        register(
https://github.com/mash-up-kr/TwoToo_iOS/pull/4/commits/bd7b636111f959bcc44d38cecc5ab426009b4ed3
아 맞네요 수정완료!

2023-06-13 09:09 UTC, kimkyunghun3 commented on Core/Util/Sources/Util/SceneUtils/UICollectionView.swift
> +            fatalError("잘못된 header입니다.")
https://github.com/mash-up-kr/TwoToo_iOS/pull/4/commits/d073a91f2662aea63182eddc8b26bd62d91331ea
아 좋네요! 말씀하신대로 바꿨어요!

2023-06-13 09:10 UTC, kimkyunghun3 commented on Core/Util/Sources/Util/SceneUtils/UICollectionView.swift
> +            fatalError("잘못된 footer입니다.")
https://github.com/mash-up-kr/TwoToo_iOS/commit/d073a91f2662aea63182eddc8b26bd62d91331ea
같이 변경했어요~

2023-06-13 09:10 UTC, kimkyunghun3 commented on Core/Util/Sources/Util/SceneUtils/UICollectionView.swift
> +            fatalError("잘못된 cell입니다.")
이것도 동일한 커밋에서 변경!

2023-06-13 09:54 UTC, gunoooo requested changes
수고하셨습니다~ 리뷰 확인 부탁드립니다.
공통 함수들이다 보니 함수 위에 주석을 더 써주시면 사용할 때 인지하기 쉬울거 같습니다.

2023-06-13 09:54 UTC, gunoooo commented on Core/Util/Sources/Util/SceneUtils/CodeBased.swift
> +protocol CodeBased {
`public`이 되어야지 다른 곳에서 사용 가능할거 같네요

2023-06-13 09:54 UTC, gunoooo commented on Core/Util/Sources/Util/SceneUtils/DateFormatter.swift
> +//  DateFormatter.swift
`SceneUtils` 폴더를 만들고 감싼 이유가 무엇일까요?
`DateFormatter`는 화면 이외에도 사용 가능할거 같은 유틸이네요

2023-06-13 09:54 UTC, gunoooo commented on Core/Util/Sources/Util/SceneUtils/CodeBased.swift
> +    func attribute()
되게 공통적으로 사용될거 같은데 함수에 대한 주석을 명확하게 써야할거 같아요

2023-06-13 09:54 UTC, gunoooo commented on Core/Util/Sources/Util/SceneUtils/CodeBased.swift
> +protocol CodeBased {
`CodeBased` 라는 네이밍이 공통 `Component`에만 사용될거 같은 느낌을 주진 않네요. `UIComponentBased` 같이 UI 요소에 사용한다는 의미를 명확하게 전달하는게 어떨까요?

2023-06-13 09:54 UTC, gunoooo commented on Core/Util/Sources/Util/SceneUtils/DateFormatter.swift
> +    func fullStringDate(_ type: FormatType = .yearMonthDay) -> Date {
(format 함수) 이런 함수들은 테스트 코드로 여러 케이스를 명세해주면,
안정성도 높아지고 사용법을 인지하기 쉬울거 같네요

2023-06-13 10:29 UTC, julia0926 approved these changes

2023-06-14 01:52 UTC, julia0926 commented on Core/Util/Sources/Util/SceneUtils/DateFormatter.swift
> +    func format(_ type: FormatType) -> String {
아하 그렇네요! 설명 감사합니다🙇🏻‍♀️

2023-06-14 10:49 UTC, kimkyunghun3 commented on Core/Util/Sources/Util/SceneUtils/UICollectionView.swift
> +    func registerCell(_ cellClass: UICollectionViewCell.Type) {
https://github.com/mash-up-kr/TwoToo_iOS/pull/4/commits/21a5b26647f5b0d12294d53cd11082988e4257f9
괜찮은거같아서 type으로 다 통일했어요!

2023-06-14 10:50 UTC, kimkyunghun3 commented on Core/Util/Sources/Util/SceneUtils/UITableView+.swift
> +    func registerCell(_ cellClass: UITableViewCell.Type) {
위 코멘트에 남겼습니다!

2023-06-14 10:50 UTC, kimkyunghun3 commented on Core/Util/Sources/Util/SceneUtils/UICollectionView.swift
> +        type: T.Type,
이유가 없어서 통일성있게 맞췄습니다!

2023-06-14 10:50 UTC, kimkyunghun3 commented on Core/Util/Sources/Util/SceneUtils/CodeBased.swift
> +protocol CodeBased {
https://github.com/mash-up-kr/TwoToo_iOS/pull/4/commits/c5b886667c670534e48606002bb032f69b5d515b
그게 더 직관적이네요! 바꿧ㅅ습니다

2023-06-14 10:51 UTC, kimkyunghun3 commented on Core/Util/Sources/Util/SceneUtils/CodeBased.swift
> +    func attribute()
https://github.com/mash-up-kr/TwoToo_iOS/pull/4/commits/c5b886667c670534e48606002bb032f69b5d515b
설명 더 추가했습니다!

2023-06-14 10:52 UTC, kimkyunghun3 commented on Core/Util/Sources/Util/SceneUtils/DateFormatter.swift
> +//  DateFormatter.swift
Scene에서 사용한다고 생각했는데 그게 아닌거같네요
Scene관련 Util로 묶어두면 어떨가 생각하고 폴더로 만들어서 감쌌는데 다른 의견 있으면 말씀해주시면 감사하겠습니다!
일단 DateFormatter, Optional는 그 외에서도 사용하는 거 같아서 밖으로 뺴두었습니다.

2023-06-14 12:26 UTC, kimkyunghun3 commented on Core/Util/Sources/Util/SceneUtils/DateFormatter.swift
> +    func fullStringDate(_ type: FormatType = .yearMonthDay) -> Date {
https://github.com/mash-up-kr/TwoToo_iOS/pull/4/commits/5b337d7b1ca39fdb01c2e5c8dd2c873114b59007
설명 과 케이스 더 추가했는데 괜찮을까요?!

2023-06-14 13:15 UTC, gunoooo approved these changes
LGTM
확인했습니다~!

2023-06-14 13:17 UTC, merged