챌린지 확인 화면 UI 및 비즈니스 로직 구현
mash-up-kr/TwoToo_iOS pull request #55
Opened 2023-07-24 08:30 UTC by kimkyunghun3

## 개요
챌린지 확인 화면 UI 및 비즈니스 로직을 구현합니다.

## 변경사항
- 챌린지 확인 화면 UI
- 챌린지 확인 화면 비즈니스 로직

## 스크린샷

수락|확인 |생성|
---|---|---|
![Simulator Screenshot - iPhone 14 Pro - 2023-07-24 at 17 20 30](https://github.com/mash-up-kr/TwoToo_iOS/assets/52434820/9974dc6c-c6f4-4fda-a23a-8943287f382d)|![Simulator Screenshot - iPhone 14 Pro - 2023-07-24 at 17 20 45](https://github.com/mash-up-kr/TwoToo_iOS/assets/52434820/257af075-b42d-4c5b-8df9-52cc0de69fb7)|![Simulator Screenshot - iPhone 14 Pro - 2023-07-24 at 17 20 54](https://github.com/mash-up-kr/TwoToo_iOS/assets/52434820/ae73de14-75e0-4f8c-8ed8-cb0be7805aeb)|

2023-07-27 02:06 UTC, julia0926 reviewed
LGTM~! 수고하셨슴니당 
코멘트만 확인 부탁드려요 🙇🏻‍♀️

2023-07-27 02:06 UTC, julia0926 commented on Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmViewController.swift
> +        self.challengeDateLabel.text = info.startDate + " ~ " + info.endDate
요거는 Presenter에서 처리해야 될 것 같네요~
"시작일 ~ 종료일" 하나의 String으로 넘겨줘서 VC에선 바로 받아서 사용하게끔요
아래 2개 메소드들도요!

2023-07-27 02:06 UTC, julia0926 commented on Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmViewController.swift
> +            make.bottom.equalTo(self.challengeTitleView.snp.top)
제가 이해한 디자인으로는 카드 height는 고정일 것 같은데
올려주신 스크린샷만 봤을 때는 카드 높이가 좀 짧아보입니당,,,😅

2023-07-27 07:26 UTC, kimkyunghun3 commented on Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmViewController.swift
> +            make.bottom.equalTo(self.challengeTitleView.snp.top)
https://github.com/mash-up-kr/TwoToo_iOS/pull/55/commits/104468559c9e07a588ae008799e80065d1e3e6a4
앗 그러네요 비율에 맞게 높이 지정해서 넣어놨어요! PR 내용에 재수정했어요~~

2023-07-27 07:33 UTC, kimkyunghun3 commented on Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmViewController.swift
> +        self.challengeDateLabel.text = info.startDate + " ~ " + info.endDate
https://github.com/mash-up-kr/TwoToo_iOS/pull/55/commits/d61d6b0aabc42552b91234e6801bfc29a37dd544
수정했습니다 요렇게 맞죠?!

2023-07-27 12:05 UTC, gunoooo requested changes
수고하셨습니다~!
약간의 코멘트 남겼는데 확인 부탁드릴게요

2023-07-27 12:05 UTC, gunoooo commented on Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmSceneFactory.swift
> +    public init() {}
아래 팩토리에서 init 에 넘기지 말고 Configuration 에서 주입하도록 해주세요.
값 전달을 하기 위한 역할을 가지고 있는 객체입니다.

2023-07-27 12:05 UTC, gunoooo commented on Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmWorker.swift
> +    func fetchChallengeConfirmInfo() async throws -> ChallengeConfirm.Model.ConfirmStatus {
이 함수의 용도는 뭘까요? 이미 진입점은 인터렉터 데이터스토어에서 넘겨줘서 워커 함수가 필요하진 않을거 같아요

2023-07-27 12:05 UTC, gunoooo commented on Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmWorker.swift
> +    func fetchChallengeInfo() async throws -> ChallengeConfirm.Model.ChallengeInfo {
이 또한 위 리뷰와 마찬가지로 외부에서 데이터를 가지고 오는게 아닌 이미 주입된 값을 보여주는것이기 때문에 워커 함수가 생길 필요 없을거 같아요

2023-07-27 12:17 UTC, kimkyunghun3 commented on Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmWorker.swift
> +    func fetchChallengeConfirmInfo() async throws -> ChallengeConfirm.Model.ConfirmStatus {
https://github.com/mash-up-kr/TwoToo_iOS/pull/55/commits/b469d0bc3abacaf62624c571347b17bf26a7e7a7
아 이거 그떄 이야기해주신대로 바꾼다고 바꾸고 이 함수들을 안지웠네요 삭제했습니다!

2023-07-27 12:17 UTC, kimkyunghun3 commented on Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmWorker.swift
> +    func fetchChallengeInfo() async throws -> ChallengeConfirm.Model.ChallengeInfo {
https://github.com/mash-up-kr/TwoToo_iOS/pull/55/commits/b469d0bc3abacaf62624c571347b17bf26a7e7a7
얘도 동일합니다!

2023-07-27 12:18 UTC, kimkyunghun3 commented on Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmSceneFactory.swift
> +    public init() {}
https://github.com/mash-up-kr/TwoToo_iOS/pull/55/commits/1529e4151a47c5ccac27765bc0465b517499d2f0
아 수정했습니다!!

2023-07-27 13:14 UTC, kimkyunghun3 commented on Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmSceneFactory.swift
> +    public init() {}
Configuration -> 값 전달하기 위한 역할을 가진 객체
SceneFactory -> VIP 내에 필요한 값들 초기화 생성해주는 객체

요렇게 이해했는데 맞나요?

2023-07-29 02:43 UTC, gunoooo commented on Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmSceneFactory.swift
> +    public init() {}
그쵸 맞습니다

2023-07-29 02:44 UTC, gunoooo approved these changes
LGTM
확인했습니다~!

2023-07-29 04:39 UTC, merged