꽃 선택하기 화면 UI 및 로직 구현
mash-up-kr/TwoToo_iOS pull request #57
Opened 2023-07-26 07:36 UTC by kimkyunghun3

## 개요
- 꽃 선택하기 화면 UI 및 로직을 구현합니다.

## 변경사항
- 꽃 선택하기 화면 UI
- 꽃 선택하기 화면 로직
- cgColor 메서드 추가

## 스크린샷
<img src = "https://github.com/mash-up-kr/TwoToo_iOS/assets/52434820/8b4edf06-a908-401c-9cfa-8bc3fa3ecbda" width="400" height="700">

2023-07-27 12:10 UTC, gunoooo requested changes
수고하셨습니다~!
약간의 코멘트 남겼는데 확인 부탁드릴게요

2023-07-27 12:10 UTC, gunoooo commented on Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectInteractor.swift
> +    var didEnterFlowerSelectScene: String { get }
트리거 형태가 아니라서 명칭이 좀 바뀌어야할거 같아요

2023-07-27 12:10 UTC, gunoooo commented on Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectInteractor.swift
> +    var didTriggerChallengeCreateScene: PassthroughSubject<Void, Never> { get }
이 이동 트리거들의 용도, 사용처는 어떻게 될까요?

2023-07-27 12:10 UTC, gunoooo commented on Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectInteractor.swift
> +        await self.presenter.selectFlower(model: .init(indexPath: flowerIndex))
선택된 꽃을 데이터 스토어에 저장해두어야 나중에 챌린지 생성, 수락 요청을 할때 사용할 수 있지 않을까요?

2023-07-27 12:10 UTC, gunoooo commented on Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectPresenter.swift
> +
토스트를 띄우는 등의 처리를 해주세요

2023-07-27 12:22 UTC, kimkyunghun3 commented on Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectInteractor.swift
> +    var didTriggerChallengeCreateScene: PassthroughSubject<Void, Never> { get }
흠.. 이거 홈 화면 이동 트리거 보고 여기에서 챌린지 생성완료 화면 이동 트리거도 있어야 되나 생각하긴 했는데
Rotuer에서 해주면 되는거같아서 불필요해보일거 같긴하네요
음 아직 이동 트리거가 있는 것도 있고 없는 것도 있는데 이거에 대한 구분 기준을 정확하게 모르겠습니다.. 🥲

2023-07-27 13:05 UTC, kimkyunghun3 commented on Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectPresenter.swift
> +
https://github.com/mash-up-kr/TwoToo_iOS/pull/57/commits/21aa144521773a729c7a6e6aea4749e09b9fd04a
넣었슴다

2023-07-27 13:05 UTC, kimkyunghun3 commented on Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectInteractor.swift
> +        await self.presenter.selectFlower(model: .init(indexPath: flowerIndex))
https://github.com/mash-up-kr/TwoToo_iOS/pull/57/commits/786629ba0f164646b8a8573dcd3c6b056f69df76
데이터 스토어에 저장했습니다~

2023-07-27 13:06 UTC, kimkyunghun3 commented on Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectInteractor.swift
> +    var didEnterFlowerSelectScene: String { get }
https://github.com/mash-up-kr/TwoToo_iOS/pull/57/commits/786629ba0f164646b8a8573dcd3c6b056f69df76
`enterSceneStatus` 로 수정했습니다

2023-07-29 03:02 UTC, gunoooo commented on Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectInteractor.swift
> +    var didTriggerChallengeCreateScene: PassthroughSubject<Void, Never> { get }
스트림으로 연결 지어주는 이유는 다른 객체 (Scene) 에서 구독하고 있다가 라우팅을 해주기 위한 의도이고, 다른 쪽에 라우팅 책임을 넘길 필요없는 경우에는 스트림으로 연결 지어줄 필요가 없습니다. (라우터에서 직접 하면됨)
꽃 선택하기 화면 같은 경우에는 챌린지 생성 완료 화면과 모듈 관계가 직접 연결되어있기 때문에 스트림으로 라우팅 책임을 넘길 필요없이 라우터에서 넘겨주면 됩니다.

2023-07-29 04:16 UTC, kimkyunghun3 commented on Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectInteractor.swift
> +    var didTriggerChallengeCreateScene: PassthroughSubject<Void, Never> { get }
아하 이해했습니다 감사합니다 ㅎㅎ

2023-07-29 08:14 UTC, gunoooo approved these changes
LGTM
확인했습니다~!

2023-07-29 08:14 UTC, merged